### PR TITLE
coverage testing with istanbul

### PR DESCRIPTION
**Pull request by milescrabill**
add istanbul 1.0.x (alpha for es6 + babel reasons) for coverage, add npm run cover command to get test coverage information

current coverage:
Statements   : 82.88% ( 92/111 )
Branches     : 71.21% ( 47/66 )
Functions    : 75% ( 9/12 )
Lines        : 82.08% ( 87/106 )

### CODE REVIEW

**Comment by milescrabill** [comment]
current coverage:
Statements: 88.46% ( 92/104 )
Branches: 78.33% ( 47/60 )
Functions: 75% ( 9/12 )
Lines: 87.88% ( 87/99 )

**Comment by mostlygeek** [comment]
why not use something like coveralls.io?

**Comment by milescrabill** [comment]
It seems like it might be funky to do with a public repo because it needs API keys, no?

**Comment by milescrabill** [comment]
r? @mostlygeek 

I might set up coveralls in the future, but at the moment it doesn't seem necessary

**Pull request closed without merging**
