### PR TITLE
update q and should

### PR DESCRIPTION
**Pull request by milescrabill**
breaking nothing afaik

### CODE REVIEW

**Comment by leibovic** [comment]
@milescrabill Have you looked into using Greenkeeper? https://greenkeeper.io/

**Comment by milescrabill** [comment]
I hadn't heard of it before, but I read a little into it and just enabled it to try out. Is Mozilla using Greenkeeper elsewhere?

**Comment by leibovic** [comment]
> Is Mozilla using Greenkeeper elsewhere?

Someone from cloud services would be better suited to answer this question. I don't usually work with node (at least not in my Mozilla work), so I don't know.

**Comment by milescrabill** [comment]
Merging to update Q. Updated should through Greenkeeper.

**Pull request merged**
